import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {readFile} from 'node:fs/promises';
import {reviewSummary} from '../../viewer/review_record.js';

const baseline=process.argv.includes('--baseline');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1157,height:600},deviceScaleFactor:2});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
const settled=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const state=()=>page.evaluate(()=>structuredClone(window.__tractlabTest));
const dismiss=async()=>{if(await page.locator('#reviewStatus').isVisible())await page.locator('.review-dismiss').click();};
const nearly=(actual,expected)=>actual.forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<1e-6,`${v} != ${expected[i]}`));
const upload=async record=>{
  record.summary=reviewSummary(record);
  await page.locator('#reviewFile').setInputFiles({name:'review.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(record))});
  await page.waitForFunction(()=>!document.getElementById('main').inert);
};
try{
  const url=process.argv.find(a=>a.startsWith('--url='))?.slice(6)||'http://127.0.0.1:18993/';
  await page.goto(url+'#test');
  await page.waitForFunction(()=>window.__tractlabTest?.mapReady,undefined,{timeout:120000});
  assert.equal((await state()).focusLayerKey,'bank:bank_cst_r','initial focus follows requested order');
  assert.equal((await state()).layerKeys.length,3);
  await page.screenshot({path:'/private/tmp/tractlab-v1-final-overview.png'});
  await page.locator('[data-layer-key="bank:bank_fat_r"] .map-focus').click();await settled();
  const before=await page.locator('#scene').screenshot();
  await page.locator('[data-layer-key="bank:bank_cst_r"] .map-focus').click();await settled();
  const after=await page.locator('#scene').screenshot();
  const focusChangesScene=!before.equals(after);
  await page.evaluate(async()=>{
    const THREE=await import('/vendor/three.module.js');window.__v1Disposals=0;
    const old=THREE.BufferGeometry.prototype.dispose;
    THREE.BufferGeometry.prototype.dispose=function(){window.__v1Disposals++;return old.call(this);};
    const setAttribute=THREE.BufferGeometry.prototype.setAttribute;window.__v1ColorAttributes=0;
    THREE.BufferGeometry.prototype.setAttribute=function(name,attribute){if(name==='color')window.__v1ColorAttributes++;return setAttribute.call(this,name,attribute);};
  });
  const target=await page.evaluate(()=>window.__tractlabPickProbe.projectTarget('bank:bank_cst_r'));
  assert.ok(target,'CST has a visible, pickable streamline');await page.mouse.click(target.x,target.y);
  await page.waitForFunction(()=>window.__tractlabTest.selected);
  const pin=await page.evaluate(()=>window.__tractlabTest.selected);
  assert.equal(pin.sourcePopulation,'bank:bank_cst_r');
  await page.locator('#btnLocateStreamline').click();await settled();
  assert.equal(await page.locator('#slicePlane').inputValue(),'cor');
  assert.equal(await page.locator('#ccor').isVisible(),true);
  assert.equal(await page.locator('#cax').isVisible(),false);
  await page.screenshot({path:'/private/tmp/tractlab-v1-final-mri.png'});
  await page.locator('#expand-cor').click();await settled();
  await page.locator('#tab-display').click();await settled();
  await page.evaluate(()=>{window.__v1Disposals=0;window.__v1ColorAttributes=0;});
  await page.locator('#btnDir').click();await settled();
  const colourState=await page.evaluate(()=>({selected:window.__tractlabTest.selected,disposed:window.__v1Disposals,colourAttributes:window.__v1ColorAttributes,copy:document.getElementById('caseMap').innerText}));
  console.log(JSON.stringify({baseline,focusChangesScene,colourState}));
  if(!baseline){
    assert.ok(focusChangesScene,'focus must change the scene label, leader and anchor');
    assert.equal((await state()).pipeline.focusOutlinePasses,0,'focus must not add pale fibre contours');
    assert.deepEqual(colourState.selected,pin,'changing colour preserves the exact pinned source');
    assert.equal(colourState.disposed,0,'colour updates do not rebuild geometry');
    assert.equal(colourState.colourAttributes,0,'colour changes reuse the owned GPU attribute');
    assert.doesNotMatch(colourState.copy,/proximity in colour/,'caption follows direction mode');
    assert.equal(await page.locator('#btnSaveReview').isVisible(),true);
    assert.equal(await page.locator('#btnOpenReview').isVisible(),true);
    const saving=page.waitForEvent('download',{timeout:15000});await page.locator('#btnSaveReview').click();
    const download=await saving;
    const record=JSON.parse(await readFile(await download.path(),'utf8'));
    await page.waitForFunction(()=>!document.getElementById('main').inert);
    assert.equal(record.view.pin.sourceIndex,pin.sourceIndex);
    assert.equal(record.schemaVersion,3);
    assert.equal(record.view.focusLayerKey,'bank:bank_cst_r');
    assert.equal(record.view.colour,'direction');
    assert.match(record.summary,/local residual error (?:is|remains) unmeasured/i);
    const summaryDownload=page.waitForEvent('download');
    await page.locator('#reviewStatus summary').click();await page.getByRole('button',{name:'Download summary',exact:true}).click();
    assert.equal(await readFile(await (await summaryDownload).path(),'utf8'),record.summary);
    await page.reload();await page.waitForFunction(()=>window.__tractlabTest?.mapReady,undefined,{timeout:120000});
    await upload(structuredClone(record));
    assert.match(await page.locator('#reviewStatus').innerText(),/Review reopened from matching sources/);
    const restored=await state();
    assert.equal(restored.focusLayerKey,'bank:bank_cst_r');assert.equal(restored.selected.sourceIndex,pin.sourceIndex);
    assert.equal(restored.selected.sourcePopulation,pin.sourcePopulation);
    assert.equal(restored.map.colour,'direction');assert.deepEqual(restored.map.slices,record.view.slices);
    for(const key of ['position','target','up','offset'])nearly(restored.camera[key],record.view.camera[key]);
    assert.deepEqual(restored.viewLayout,record.view.layout);
    await dismiss();await page.screenshot({path:'/private/tmp/tractlab-v1-final-restored.png'});
    await page.locator('#tab-tools').click();await page.locator('#researchTools').evaluate(el=>el.open=true);
    const exportResponse=page.waitForResponse(r=>r.url().endsWith('/api/export/tck'));
    const exporting=page.waitForEvent('download');await page.locator('#btnExport').click();
    const exported=await exportResponse;await exporting;
    assert.equal(exported.request().postDataJSON().bankId,'bank_cst_r');
    assert.equal(exported.headers()['x-banksourcehash'],record.banks.find(b=>b.bankId==='bank_cst_r').sourceHash);
    for(const mutation of [r=>r.context.caseId='a-different-case',r=>r.context.caseSourceHash='0'.repeat(64),r=>r.banks[0].sourceHash='0'.repeat(64),r=>r.view.pin.sourceIndex=4294967295]){
      const invalid=structuredClone(record);mutation(invalid);await upload(invalid);
      assert.match(await page.locator('#reviewStatus').innerText(),/Review not opened/);
      const retained=await state();assert.equal(retained.selected.sourceIndex,pin.sourceIndex);
      assert.deepEqual(retained.layerKeys,restored.layerKeys);nearly(retained.camera.position,restored.camera.position);await dismiss();
    }
    // Schema 2 saves painted ROI state instead of refusing it.
    await page.locator('#btnInspectMRI').click();await settled();
    await page.locator('#btnPaintMode').click();
    const paintSaving=page.waitForEvent('download',{timeout:15000});await page.locator('#btnSaveReview').click();
    const painted=JSON.parse(await readFile(await (await paintSaving).path(),'utf8'));
    await page.waitForFunction(()=>!document.getElementById('main').inert);
    assert.equal(painted.paint.paintMode,true,'paint mode is saved, not refused');
    assert.equal(painted.paint.grid.gridId,painted.context.gridId);
    await dismiss();await page.locator('#btnPaintMode').click();await page.locator('#btnInspectMRI').click();await settled();
    await page.locator('#btnResetView').click();await settled();const overview=await state();
    await page.locator('#expand-cor').click();await settled();const expanded=await state();
    assert.notDeepEqual(expanded.camera.position,overview.camera.position,'overview adapts to expanded anatomy');
    await page.locator('#expand-cor').click();await settled();nearly((await state()).camera.position,overview.camera.position);
    const rect=await page.locator('#gl').boundingBox();
    await page.mouse.move(rect.x+rect.width*.58,rect.y+rect.height*.5);await page.mouse.down();
    await page.mouse.move(rect.x+rect.width*.68,rect.y+rect.height*.55,{steps:16});await page.mouse.up();
    await page.waitForFunction(()=>window.__tractlabTest?.pipeline?.interacting===false);await settled();
    const manual=await state();assert.equal(manual.camera.autoFrame,false);
    await page.locator('#btnSlices').click();await settled();nearly((await state()).camera.position,manual.camera.position);
    await page.locator('#btnSlices').click();await settled();nearly((await state()).camera.position,manual.camera.position);
    await page.locator('#btnResetView').click();await settled();assert.equal((await state()).camera.autoFrame,true);
    await page.locator('#anatomyResize').focus();await page.keyboard.press('ArrowUp');await page.keyboard.press('ArrowUp');await settled();
    const adjustedOverview=(await state()).viewLayout.dockFraction;
    await page.locator('#expand-cor').click();await settled();
    const savingExpanded=page.waitForEvent('download');await page.locator('#btnSaveReview').click();
    const expandedRecord=JSON.parse(await readFile(await (await savingExpanded).path(),'utf8'));await page.waitForFunction(()=>!document.getElementById('main').inert);await dismiss();
    await page.locator('#expand-cor').click();await upload(expandedRecord);await dismiss();
    await page.locator('#expand-cor').click();await settled();assert.equal((await state()).viewLayout.dockFraction,adjustedOverview,'return from restored inspection retains the previous dock size');
    await page.setViewportSize({width:851,height:507});await settled();
    await page.locator('#side').evaluate(el=>Promise.all(el.getAnimations().map(animation=>animation.finished.catch(()=>{}))));await settled();
    assert.ok(await page.locator('#side').evaluate(el=>el.getBoundingClientRect().right<=0),'compact drawer is completely outside the closed view');
    assert.equal(await page.locator('#btnSaveReview').isVisible(),true);assert.equal(await page.locator('#btnOpenReview').isVisible(),true);
    await page.screenshot({path:'/private/tmp/tractlab-v1-final-compact.png'});
    console.log(JSON.stringify({journey:'passed',banks:record.banks.map(b=>({bankId:b.bankId,p5:b.p5,sourceHash:b.sourceHash})),pin:record.view.pin,buildId:record.context.buildId}));
    const incompatible=await browser.newPage();
    await incompatible.route(url,async route=>{
      const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace(/<meta name="tractlab-(?:build|protocol)"[^>]*>/g,'')});
    });
    await incompatible.goto(url);
    await incompatible.waitForFunction(()=>document.querySelector('#emptyState p')?.textContent.includes('Incompatible server'));
    assert.match(await incompatible.locator('#emptyState').innerText(),/Restart TractLab/);await incompatible.close();
  }
  assert.deepEqual(errors,[]);
}catch(error){
  console.error(await page.locator('body').innerText());throw error;
}finally{await browser.close();}
