// Surgeon-authored pt-BR tour; patient mode applies only saved, reviewed content.
function captureView(){return {layout:state.maximized||state.activeView,crosshair_ras:state.crosshair.slice(),window:{volume:state.base,center:state.window.center,width:state.window.width},camera:{...state.camera,zoom:state.zoom.three},visible_masks:visibleMasks().map(m=>m.id),visible_annotations:visibleAnnotations().map(a=>a.id)}}
function addTourStep(title,text){if(state.mode==='patient')throw Error('Edição indisponível');const step={id:'step-'+crypto.randomUUID(),title,text,view:captureView()};state.manifest.tour.push(step);renderStepList();return step}
function applyTourStep(index){
  const tour=state.manifest.tour;if(!tour.length){state.tourIndex=0;renderTourPanel();return}
  state.tourIndex=clamp(index,0,tour.length-1);const step=tour[state.tourIndex],view=step.view||{};
  if(view.crosshair_ras)state.crosshair=view.crosshair_ras.slice();if(view.window){if(state.volumes.has(view.window.volume))state.base=view.window.volume;state.window={center:view.window.center,width:view.window.width}}
  if(view.camera){state.camera={yaw:view.camera.yaw??state.camera.yaw,pitch:view.camera.pitch??state.camera.pitch};state.zoom.three=view.camera.zoom??state.zoom.three}
  state.tourMaskFilter=view.visible_masks??null;state.tourAnnotationFilter=view.visible_annotations??[];
  const layout=view.layout==='3d'?'three':view.layout||'three';state.activeView=['axial','coronal','sagittal','three'].includes(layout)?layout:'three';
  for(const el of document.querySelectorAll('.view'))el.classList.toggle('active',el.dataset.view===state.activeView);
  state.glData.maskDirty=true;renderTourPanel();requestAnimationFrame(renderAll);return step;
}
function setMode(mode){if(!['patient','surgeon'].includes(mode))throw Error('Modo inválido');state.mode=mode;localizeStatic();document.body.classList.toggle('patient',mode==='patient');$('mode-button').textContent=mode==='patient'?tr('surgeon'):tr('patient');$('workspace').classList.toggle('single',mode==='surgeon'&&!!state.maximized);if(mode==='patient'){applyTourStep(state.tourIndex)}else{state.tourMaskFilter=null;state.tourAnnotationFilter=null;for(const el of document.querySelectorAll('.view'))el.classList.toggle('active',!state.maximized||el.dataset.view===state.maximized);state.glData.maskDirty=true;renderAll()}return mode}
function renderTourPanel(){const tour=state.manifest.tour,step=tour[state.tourIndex];$('step-count').textContent=step?'● '.repeat(state.tourIndex+1)+'○ '.repeat(tour.length-state.tourIndex-1):'';$('step-title').textContent=step?step.title:'';$('step-text').textContent=step?step.text:tr('noTour');$('prev-step').disabled=!step||state.tourIndex===0;$('next-step').disabled=!step||state.tourIndex>=tour.length-1}
function renderStepList(){const list=$('step-list');list.replaceChildren();for(const [i,step] of state.manifest.tour.entries()){const div=document.createElement('div');div.className='step-card';const title=document.createElement('span');title.textContent=`${i+1}. ${step.title}`;const row=document.createElement('div');row.className='row';row.append(title);for(const [text,delta] of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.textContent=text;b.disabled=i+delta<0||i+delta>=state.manifest.tour.length;b.onclick=()=>{const t=state.manifest.tour;[t[i],t[i+delta]]=[t[i+delta],t[i]];renderStepList()};row.append(b)}const del=document.createElement('button');del.textContent=UI_COPY[state.manifest.locale==='en'?'en':'pt-BR'].delete;del.onclick=()=>{state.manifest.tour.splice(i,1);renderStepList()};row.append(del);div.append(row);list.append(div)}}
