// Controls, loading states, and event wiring.
const CT_PRESETS=[['Cérebro',40,80],['Subdural',75,215],['AVC',35,40],['Partes moles',40,400],['Osso',600,2800],['Osso temporal',700,4000]];
function option(select,value,label){const el=document.createElement('option');el.value=value;el.textContent=label;select.append(el)}
function updatePresets(){const vol=state.volumes.get(state.base),select=$('preset');select.replaceChildren();let presets=vol.meta.window_presets||[];if(vol.meta.kind==='CT'){const names=new Set(presets.map(p=>p.name));presets=[...presets,...CT_PRESETS.filter(p=>!names.has(p[0])).map(([name,center,width])=>({name,center,width}))]}else{const s=vol.meta.stats||{};presets=[{name:'Auto',center:((s.p01??0)+(s.p99??65535))/2,width:Math.max(1,(s.p99??65535)-(s.p01??0))},...presets]}const s=vol.meta.stats||{},span=Math.max(100,(s.max??65535)-(s.min??0));$('level').min=Math.min(-1200,s.min??0);$('level').max=Math.max(2000,s.max??65535);$('width').max=Math.max(4000,span*2);for(const [i,p] of presets.entries())option(select,String(i),p.name);option(select,'manual',UI_COPY[state.manifest.locale==='en'?'en':'pt-BR'].manual);select._presets=presets;select.value='manual';syncWindow();renderHistogram()}
function syncWindow(){$('level').value=state.window.center;$('level-number').value=Number(state.window.center.toFixed(1));$('width').value=state.window.width;$('width-number').value=Number(state.window.width.toFixed(1));$('preset').value='manual'}
function renderHistogram(){const canvas=$('histogram'),ctx=canvas.getContext('2d'),vol=state.volumes.get(state.base),values=vol.data,stats=vol.meta.stats||{},min=stats.p01??stats.min??0,max=stats.p99??stats.max??65535,bins=new Uint32Array(100);for(let i=0;i<values.length;i+=Math.max(1,Math.floor(values.length/50000))){const v=values[i]*vol.meta.slope+vol.meta.intercept,index=clamp(Math.floor((v-min)/Math.max(1,max-min)*bins.length),0,bins.length-1);bins[index]++}const top=Math.max(...bins,1);ctx.fillStyle='#0a0d13';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#C9A84C';for(let i=0;i<bins.length;i++)ctx.fillRect(i*canvas.width/bins.length,canvas.height-bins[i]/top*canvas.height,canvas.width/bins.length,canvas.height)}
function renderMaskList(){const list=$('mask-list');list.replaceChildren();for(const meta of state.manifest.masks){const row=document.createElement('div');row.className='row';const label=document.createElement('span');label.textContent=`${meta.label} · ${Number(meta.volume_ml||0).toFixed(2)} mL`;const toggle=document.createElement('label');const box=document.createElement('input');box.type='checkbox';box.checked=!!meta.reviewed;box.onchange=()=>{meta.reviewed=box.checked;state.glData.maskDirty=true;renderAll()};toggle.append(box,document.createTextNode(tr('reviewed')));row.append(label,toggle);list.append(row)}}
function initUI(){
  localizeStatic();
  $('case-label').textContent=state.manifest.case?.label||'Caso';$('anonymous').textContent='Anonimizado';$('version-badge').textContent='v'+state.manifest.version;
  for(const meta of state.manifest.volumes){option($('base-volume'),meta.id,meta.label);option($('overlay-volume'),meta.id,meta.label)}$('base-volume').value=state.base;$('overlay-volume').insertBefore(new Option(UI_COPY[state.manifest.locale==='en'?'en':'pt-BR'].none,''),$('overlay-volume').firstChild);$('overlay-volume').value='';
  updatePresets();renderMaskList();renderAnnotationList();renderStepList();installCanvasGestures();
  $('base-volume').onchange=e=>{state.base=e.target.value;const vol=state.volumes.get(state.base),p=vol.meta.window_presets?.[0],s=vol.meta.stats||{};state.window=p?{center:p.center,width:p.width}:{center:((s.p01??0)+(s.p99??65535))/2,width:Math.max(1,(s.p99??65535)-(s.p01??0))};updatePresets();renderAll()};
  $('overlay-volume').onchange=e=>{state.overlay=e.target.value||null;renderAll()};$('fusion-opacity').oninput=e=>{state.overlayOpacity=Number(e.target.value)/100;renderAll()};$('colormap').onchange=e=>{state.colormap=e.target.value;renderAll()};
  $('preset').onchange=e=>{const p=e.target._presets[Number(e.target.value)];if(p){state.window={center:p.center,width:p.width};syncWindow();e.target.value=String(e.target._presets.indexOf(p));renderAll()}};
  for(const [name,key] of [['level','center'],['width','width']])for(const id of [name,name+'-number'])$(id).oninput=e=>{state.window[key]=name==='width'?Math.max(1,Number(e.target.value)):Number(e.target.value);syncWindow();renderAll()};
  $('invert').onchange=e=>{state.invert=e.target.checked;renderAll()};$('slab-mode').onchange=e=>{state.slab=e.target.value;renderAll()};$('slab-mm').onchange=e=>{state.slabMm=clamp(Number(e.target.value),1,40);renderAll()};$('oblique').oninput=e=>{state.oblique=Number(e.target.value);renderAll()};
  $('mode3d').onchange=e=>{state.mode3d=e.target.value;render3D()};$('cut3d').onchange=e=>{state.cut3d=e.target.value;render3D()};$('threshold3d').oninput=e=>{state.threshold3d=Number(e.target.value);render3D()};$('opacity3d').oninput=e=>{state.opacity3d=Number(e.target.value)/100;render3D()};$('planes3d').onchange=e=>{state.planes3d=e.target.checked;render3D()};
  $('tool').onchange=e=>{state.tool=e.target.value;state.pending=[]};$('reset-view').onclick=()=>{state.oblique=0;state.zoom={axial:1,coronal:1,sagittal:1,three:1};state.pan={axial:[0,0],coronal:[0,0],sagittal:[0,0]};state.camera={yaw:.45,pitch:.2};$('oblique').value=0;renderAll()};
  $('mode-button').onclick=()=>setMode(state.mode==='surgeon'?'patient':'surgeon');$('save-button').onclick=()=>save().catch(e=>status('error',tr('bad')+' '+e.message));$('shot-button').onclick=screenshot;
  $('add-step').onclick=()=>{const title=$('new-step-title').value.trim(),text=$('new-step-text').value.trim();if(!title||!text)return;addTourStep(title,text);$('new-step-title').value='';$('new-step-text').value=''};
  $('prev-step').onclick=()=>applyTourStep(state.tourIndex-1);$('next-step').onclick=()=>applyTourStep(state.tourIndex+1);
  for(const button of document.querySelectorAll('[data-max]'))button.onclick=()=>{const view=button.dataset.max;state.maximized=state.maximized===view?null:view;$('workspace').classList.toggle('single',!!state.maximized);for(const el of document.querySelectorAll('.view'))el.classList.toggle('active',!state.maximized||el.dataset.view===state.maximized);state.activeView=view;requestAnimationFrame(renderAll)};
  new ResizeObserver(()=>{if(state.status==='ready')renderAll()}).observe($('workspace'));
}
function start(){loadCapsule()}
